from datetime import datetime
from uuid import uuid4

from app.core.database import database


def criar_todas_as_clinicas_no_firestore():
    collection = database.collection('clinics')
    new_data = []
    data = [
        {
            'bairro': 'Boa Vista',
            'cep': '50070-330',
            'cidade': 'Recife',
            'clinica': 'Clínica Casa do Bolo',
            'contato': '81994251245',
            'email': 'atendimento@casadobolo.com.br',
            'endereco_atendimento': 'Rua Marques Amorim, 239-9 - Boa Vista, Recife - PE, 50070-330',
            'estado': 'PE',
            'lat': '-34.889934189460900',
            'long': '-8.06131185393038000',
            'pessoas': 'João da Cunha Costa',
            'profissao': 'Fisioterapeuta',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Parnamirim',
            'cep': '52060-000',
            'cidade': 'Recife',
            'clinica': 'Clínica XPTO',
            'contato': '8199324251',
            'email': 'eduardo.gomes@xpto.com.br',
            'endereco_atendimento': 'Av. Parnamirim, 371 - Parnamirim',
            'estado': 'PE',
            'lat': '-34.90955510331460',
            'long': '-8.03392702936235',
            'pessoas': 'Eduardo Gomes Santos',
            'profissao': 'Fisioterapeuta',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Jaqueira',
            'cep': '52000-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Doces Sonhos',
            'contato': '81991234567',
            'email': 'docessonhos@email.com',
            'endereco_atendimento': 'Rua das Flores, 123 - Jaqueira, Recife - PE, 52000-000',
            'estado': 'PE',
            'lat': '-34.911234',
            'long': '-8.047890',
            'pessoas': 'Maria da Silva',
            'profissao': 'Nutricionista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Boa Viagem',
            'cep': '51000-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Estar',
            'contato': '81987654321',
            'email': 'contato@bemestarclinicape.com',
            'endereco_atendimento': 'Rua dos Coqueiros, 456 - Boa Viagem, Recife - PE, 51000-000',
            'estado': 'PE',
            'lat': '-34.897654',
            'long': '-8.109876',
            'pessoas': 'Paula Ferreira',
            'profissao': 'Psicólogo',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Ipsep',
            'cep': '50000-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Total',
            'contato': '81981122334',
            'email': 'luiz.saude@gmail.com',
            'endereco_atendimento': 'Rua das Palmeiras, 789 - Ipsep, Recife - PE, 50000-000',
            'estado': 'PE',
            'lat': '-34.913456',
            'long': '-8.050000',
            'pessoas': 'Luiz Carlos',
            'profissao': 'Cardiologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Bongi',
            'cep': '53000-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Viver',
            'contato': '81980002222',
            'email': 'anaviver@clinicabemviver.com',
            'endereco_atendimento': 'Av. da Esperança, 555 - Bongi, Recife - PE, 53000-000',
            'estado': 'PE',
            'lat': '-34.939876',
            'long': '-8.050987',
            'pessoas': 'Ana Santos',
            'profissao': 'Psiquiatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Boa Vista',
            'cep': '51020-000',
            'cidade': 'Recife',
            'clinica': 'Clínica da Beleza',
            'contato': '81985556677',
            'email': 'marcosbeleza@clinicabeleza.com.br',
            'endereco_atendimento': 'Rua das Orquídeas, 321 - Boa Vista, Recife - PE, 51020-000',
            'estado': 'PE',
            'lat': '-34.902345',
            'long': '-8.056789',
            'pessoas': 'Marcos Oliveira',
            'profissao': 'Dermatologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Madalena',
            'cep': '50670-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Cuidar',
            'contato': '81987776655',
            'email': 'isabelacuidar@email.com',
            'endereco_atendimento': 'Rua das Rosas, 654 - Madalena, Recife - PE, 50670-000',
            'estado': 'PE',
            'lat': '-34.911111',
            'long': '-8.045678',
            'pessoas': 'Isabela Lima',
            'profissao': 'Odontologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Boa Viagem',
            'cep': '51111-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Esperança',
            'contato': '81983334455',
            'email': 'pedro.esperanca@clinicaesperanca.com',
            'endereco_atendimento': 'Av. Boa Viagem, 987 - Boa Viagem, Recife - PE, 51111-000',
            'estado': 'PE',
            'lat': '-34.900987',
            'long': '-8.119876',
            'pessoas': 'Pedro Santos',
            'profissao': 'Ortopedista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'San Martin',
            'cep': '50780-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Feliz',
            'contato': '81989997788',
            'email': 'juliafeliz@saudeclinica.com',
            'endereco_atendimento': 'Rua das Violetas, 222 - San Martin, Recife - PE, 50780-000',
            'estado': 'PE',
            'lat': '-34.932345',
            'long': '-8.042345',
            'pessoas': 'Júlia Fernandes',
            'profissao': 'Pediatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Torre',
            'cep': '50030-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Vida Plena',
            'contato': '81981112233',
            'email': 'amandavida@clinicavida.com',
            'endereco_atendimento': 'Rua das Palmas, 123 - Torre, Recife - PE, 50030-000',
            'estado': 'PE',
            'lat': '-34.904321',
            'long': '-8.048765',
            'pessoas': 'Amanda Silva',
            'profissao': 'Psicólogo',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Casa Amarela',
            'cep': '52050-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Serenidade',
            'contato': '81983332211',
            'email': 'fernandoserenidade@email.com',
            'endereco_atendimento': 'Rua das Mangueiras, 456 - Casa Amarela, Recife - PE, 52050-000',
            'estado': 'PE',
            'lat': '-34.917654',
            'long': '-8.019876',
            'pessoas': 'Fernando Santos',
            'profissao': 'Fisioterapeuta',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Tamarineira',
            'cep': '52100-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem-estar Total',
            'contato': '81987778899',
            'email': 'marina.bemestar@gmail.com',
            'endereco_atendimento': 'Av. das Acácias, 789 - Tamarineira, Recife - PE, 52100-000',
            'estado': 'PE',
            'lat': '-34.910987',
            'long': '-8.018765',
            'pessoas': 'Marina Lima',
            'profissao': 'Nutricionista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Encruzilhada',
            'cep': '52040-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Harmonia',
            'contato': '81984443322',
            'email': 'ricardoharmonia@saudeclinicarecife.com',
            'endereco_atendimento': 'Rua dos Girassóis, 555 - Encruzilhada, Recife - PE, 52040-000',
            'estado': 'PE',
            'lat': '-34.903456',
            'long': '-8.016543',
            'pessoas': 'Ricardo Oliveira',
            'profissao': 'Cardiologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Espinheiro',
            'cep': '52021-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Viver Feliz',
            'contato': '81986667788',
            'email': 'simonefeliz@bemviverclinicape.com.br',
            'endereco_atendimento': 'Av. dos Ipês, 987 - Espinheiro, Recife - PE, 52021-000',
            'estado': 'PE',
            'lat': '-34.911111',
            'long': '-8.014321',
            'pessoas': 'Simone Santos',
            'profissao': 'Psiquiatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Afogados',
            'cep': '50710-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Sorriso Perfeito',
            'contato': '81982223344',
            'email': 'marcossorriso@email.com',
            'endereco_atendimento': 'Rua das Violetas, 222 - Afogados, Recife - PE, 50710-000',
            'estado': 'PE',
            'lat': '-34.919876',
            'long': '-8.018765',
            'pessoas': 'Marcos Lima',
            'profissao': 'Odontologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Boa Vista',
            'cep': '50050-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Esperança de Vida',
            'contato': '81985556677',
            'email': 'sofiaesperanca@clinicarecife.com',
            'endereco_atendimento': 'Av. Boa Vista, 123 - Boa Vista, Recife - PE, 50050-000',
            'estado': 'PE',
            'lat': '-34.892345',
            'long': '-8.063456',
            'pessoas': 'Sofia Fernandes',
            'profissao': 'Ortopedista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Piedade',
            'cep': '51300-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Infantil',
            'contato': '81989998877',
            'email': 'carlasaudeinfantil@email.com',
            'endereco_atendimento': 'Rua dos Anjos, 321 - Piedade, Recife - PE, 51300-000',
            'estado': 'PE',
            'lat': '-34.892345',
            'long': '-8.067654',
            'pessoas': 'Carla Santos',
            'profissao': 'Pediatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Parnamirim',
            'cep': '52070-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Cuidado',
            'contato': '81983335566',
            'email': 'pedrocuidado@clinicabemcuidado.com.br',
            'endereco_atendimento': 'Av. Parnamirim, 555 - Parnamirim, Recife - PE, 52070-000',
            'estado': 'PE',
            'lat': '-34.908765',
            'long': '-8.042345',
            'pessoas': 'Pedro Lima',
            'profissao': 'Fisioterapeuta',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Bongi',
            'cep': '50721-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Viver Melhor',
            'contato': '81987776655',
            'email': 'isabelavivermelhor@clinicarecife.com',
            'endereco_atendimento': 'Rua das Oliveiras, 456 - Bongi, Recife - PE, 50721-000',
            'estado': 'PE',
            'lat': '-34.904321',
            'long': '-8.038765',
            'pessoas': 'Isabela Santos',
            'profissao': 'Nutricionista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Boa Viagem',
            'cep': '51100-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde da Mulher',
            'contato': '81984448877',
            'email': 'maria.saude@clinicadamulher.com',
            'endereco_atendimento': 'Av. Boa Viagem, 987 - Boa Viagem, Recife - PE, 51100-000',
            'estado': 'PE',
            'lat': '-34.903456',
            'long': '-8.118765',
            'pessoas': 'Maria Fernanda',
            'profissao': 'Ginecologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Caxangá',
            'cep': '50711-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Vida',
            'contato': '81981115544',
            'email': 'felipebemvida@email.com',
            'endereco_atendimento': 'Rua das Palmeiras, 987 - Caxangá, Recife - PE, 50711-000',
            'estado': 'PE',
            'lat': '-34.908765',
            'long': '-8.060987',
            'pessoas': 'Felipe Lima',
            'profissao': 'Odontologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Estância',
            'cep': '50810-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde em Dia',
            'contato': '81983334455',
            'email': 'juliasaude@clinicasaudeemdia.com.br',
            'endereco_atendimento': 'Av. das Rosas, 321 - Estância, Recife - PE, 50810-000',
            'estado': 'PE',
            'lat': '-34.901234',
            'long': '-8.070987',
            'pessoas': 'Júlia Santos',
            'profissao': 'Psiquiatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'San Martin',
            'cep': '50700-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Vida Feliz',
            'contato': '81989997788',
            'email': 'carlosvidafeliz@email.com',
            'endereco_atendimento': 'Rua dos Jardins, 222 - San Martin, Recife - PE, 50700-000',
            'estado': 'PE',
            'lat': '-34.897654',
            'long': '-8.067654',
            'pessoas': 'Carlos Oliveira',
            'profissao': 'Cardiologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Imbiribeira',
            'cep': '51120-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Cuidar',
            'contato': '81981112233',
            'email': 'marinacuidar@clinicarecife.com',
            'endereco_atendimento': 'Av. dos Lírios, 456 - Imbiribeira, Recife - PE, 51120-000',
            'estado': 'PE',
            'lat': '-34.901234',
            'long': '-8.065432',
            'pessoas': 'Marina Santos',
            'profissao': 'Psicanalista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Encruzilhada',
            'cep': '52080-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde em Família',
            'contato': '81983332211',
            'email': 'luizsaudeemfamilia@email.com',
            'endereco_atendimento': 'Rua das Acácias, 555 - Encruzilhada, Recife - PE, 52080-000',
            'estado': 'PE',
            'lat': '-34.903456',
            'long': '-8.064321',
            'pessoas': 'Luiz Oliveira',
            'profissao': 'Pediatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Boa Vista',
            'cep': '50080-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Estar Total',
            'contato': '81987778899',
            'email': 'analima@bemestartotal.com.br',
            'endereco_atendimento': 'Av. da Esperança, 123 - Boa Vista, Recife - PE, 50080-000',
            'estado': 'PE',
            'lat': '-34.899876',
            'long': '-8.060987',
            'pessoas': 'Ana Lima',
            'profissao': 'Geriatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Tejipió',
            'cep': '50640-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Plena',
            'contato': '81986667788',
            'email': 'rodrigosaude@clinicasaudeplena.com',
            'endereco_atendimento': 'Rua das Flores, 789 - Tejipió, Recife - PE, 50640-000',
            'estado': 'PE',
            'lat': '-34.910987',
            'long': '-8.057654',
            'pessoas': 'Rodrigo Santos',
            'profissao': 'Dermatologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Coroado',
            'cep': '52110-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Vida Saudável',
            'contato': '81982223344',
            'email': 'marianasaudavel@email.com',
            'endereco_atendimento': 'Av. dos Coqueiros, 555 - Coroado, Recife - PE, 52110-000',
            'estado': 'PE',
            'lat': '-34.901234',
            'long': '-8.056789',
            'pessoas': 'Mariana Lima',
            'profissao': 'Nutricionista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Madalena',
            'cep': '50690-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Esperança Viva',
            'contato': '81984443322',
            'email': 'carlosesperanca@clinicarecife.com',
            'endereco_atendimento': 'Rua das Tulipas, 456 - Madalena, Recife - PE, 50690-000',
            'estado': 'PE',
            'lat': '-34.908765',
            'long': '-8.054321',
            'pessoas': 'Carlos Santos',
            'profissao': 'Fisioterapeuta',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Torre',
            'cep': '50090-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Estar Familiar',
            'contato': '81983335566',
            'email': 'sofiabemestar@email.com',
            'endereco_atendimento': 'Av. das Azaleias, 987 - Torre, Recife - PE, 50090-000',
            'estado': 'PE',
            'lat': '-34.911111',
            'long': '-8.049876',
            'pessoas': 'Sofia Lima',
            'profissao': 'Ginecologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Casa Forte',
            'cep': '52070-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Mental',
            'contato': '81987776655',
            'email': 'marcossaude@clinicasaudemental.com.br',
            'endereco_atendimento': 'Rua dos Cravos, 321 - Casa Forte, Recife - PE, 52070-000',
            'estado': 'PE',
            'lat': '-34.911111',
            'long': '-8.047890',
            'pessoas': 'Marcos Santos',
            'profissao': 'Psiquiatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Barro',
            'cep': '50730-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Cuidado',
            'contato': '81981112233',
            'email': 'pedrocuidado@clinicabemcuidado.com',
            'endereco_atendimento': 'Av. das Palmeiras, 456 - Barro, Recife - PE, 50730-000',
            'estado': 'PE',
            'lat': '-34.913456',
            'long': '-8.046789',
            'pessoas': 'Pedro Lima',
            'profissao': 'Odontopediatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'San Martin',
            'cep': '50760-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Viver Bem',
            'contato': '81985556677',
            'email': 'luanaviverbem@email.com',
            'endereco_atendimento': 'Rua dos Jasmins, 222 - San Martin, Recife - PE, 50760-000',
            'estado': 'PE',
            'lat': '-34.913456',
            'long': '-8.043210',
            'pessoas': 'Luana Santos',
            'profissao': 'Cardiologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Tamarineira',
            'cep': '52060-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Ativa',
            'contato': '81989998877',
            'email': 'joaosaudeativa@email.com',
            'endereco_atendimento': 'Av. das Magnólias, 321 - Tamarineira, Recife - PE, 52060-000',
            'estado': 'PE',
            'lat': '-34.911111',
            'long': '-8.042345',
            'pessoas': 'João Oliveira',
            'profissao': 'Ortopedista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Boa Viagem',
            'cep': '51110-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Vida Plena',
            'contato': '81984448877',
            'email': 'maria.vida@clinicavida.com',
            'endereco_atendimento': 'Rua dos Lírios, 987 - Boa Viagem, Recife - PE, 51110-000',
            'estado': 'PE',
            'lat': '-34.907654',
            'long': '-8.041234',
            'pessoas': 'Maria Fernanda',
            'profissao': 'Nutricionista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Casa Amarela',
            'cep': '52070-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Serenidade',
            'contato': '81981115544',
            'email': 'fernandoserenidade@email.com',
            'endereco_atendimento': 'Av. das Violetas, 555 - Casa Amarela, Recife - PE, 52070-000',
            'estado': 'PE',
            'lat': '-34.919876',
            'long': '-8.019876',
            'pessoas': 'Fernando Lima',
            'profissao': 'Psicólogo',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Piedade',
            'cep': '51310-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem-estar Total',
            'contato': '81983332211',
            'email': 'marinabemestar@gmail.com',
            'endereco_atendimento': 'Rua das Orquídeas, 456 - Piedade, Recife - PE, 51310-000',
            'estado': 'PE',
            'lat': '-34.919876',
            'long': '-8.065432',
            'pessoas': 'Marina Santos',
            'profissao': 'Fisioterapeuta',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Estância',
            'cep': '50820-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Harmonia',
            'contato': '81982223344',
            'email': 'ricardoharmonia@email.com',
            'endereco_atendimento': 'Av. das Tulipas, 123 - Estância, Recife - PE, 50820-000',
            'estado': 'PE',
            'lat': '-34.919876',
            'long': '-8.064321',
            'pessoas': 'Ricardo Lima',
            'profissao': 'Cardiologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Boa Vista',
            'cep': '50060-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Viver Feliz',
            'contato': '81986667788',
            'email': 'simoneviverfeliz@email.com',
            'endereco_atendimento': 'Rua dos Girassóis, 123 - Boa Vista, Recife - PE, 50060-000',
            'estado': 'PE',
            'lat': '-34.918765',
            'long': '-8.063456',
            'pessoas': 'Simone Santos',
            'profissao': 'Psiquiatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Coroado',
            'cep': '52120-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Sorriso Perfeito',
            'contato': '81981112233',
            'email': 'marcos.perfeito@clinicasorriso.com.br',
            'endereco_atendimento': 'Av. dos Cravos, 555 - Coroado, Recife - PE, 52120-000',
            'estado': 'PE',
            'lat': '-34.917654',
            'long': '-8.062345',
            'pessoas': 'Marcos Oliveira',
            'profissao': 'Odontopediatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Tejipió',
            'cep': '50650-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Esperança de Vida',
            'contato': '81983334455',
            'email': 'sofiaesperanca@clinicarecife.com',
            'endereco_atendimento': 'Rua das Margaridas, 321 - Tejipió, Recife - PE, 50650-000',
            'estado': 'PE',
            'lat': '-34.916543',
            'long': '-8.060987',
            'pessoas': 'Sofia Lima',
            'profissao': 'Ginecologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Torre',
            'cep': '50070-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Estar Familiar',
            'contato': '81987776655',
            'email': 'pedrobemestar@email.com',
            'endereco_atendimento': 'Av. das Acácias, 987 - Torre, Recife - PE, 50070-000',
            'estado': 'PE',
            'lat': '-34.915432',
            'long': '-8.058765',
            'pessoas': 'Pedro Santos',
            'profissao': 'Pediatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Encruzilhada',
            'cep': '52090-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde em Dia',
            'contato': '81985556677',
            'email': 'juliasaude@clinicasaudeemdia.com.br',
            'endereco_atendimento': 'Rua dos Ipês, 123 - Encruzilhada, Recife - PE, 52090-000',
            'estado': 'PE',
            'lat': '-34.914321',
            'long': '-8.056789',
            'pessoas': 'Júlia Lima',
            'profissao': 'Dermatologista',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Bongi',
            'cep': '50731-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Vida Feliz',
            'contato': '81989997788',
            'email': 'carlosvidafeliz@email.com',
            'endereco_atendimento': 'Av. dos Jardins, 321 - Bongi, Recife - PE, 50731-000',
            'estado': 'PE',
            'lat': '-34.913456',
            'long': '-8.054321',
            'pessoas': 'Carlos Santos',
            'profissao': 'Fisioterapeuta',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Caxangá',
            'cep': '50680-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Mental',
            'contato': '81981115544',
            'email': 'marianasaude@clinicasaudemental.com.br',
            'endereco_atendimento': 'Rua das Azaleias, 789 - Caxangá, Recife - PE, 50680-000',
            'estado': 'PE',
            'lat': '-34.912345',
            'long': '-8.052345',
            'pessoas': 'Mariana Lima',
            'profissao': 'Psicólogo',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Madalena',
            'cep': '50660-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Bem Cuidado',
            'contato': '81983335566',
            'email': 'pedrocuidado@clinicabemcuidado.com',
            'endereco_atendimento': 'Av. das Oliveiras, 555 - Madalena, Recife - PE, 50660-000',
            'estado': 'PE',
            'lat': '-34.912345',
            'long': '-8.050987',
            'pessoas': 'Pedro Lima',
            'profissao': 'Odontopediatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Boa Vista',
            'cep': '50090-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Viver Bem',
            'contato': '81982223344',
            'email': 'luanaviverbem@email.com',
            'endereco_atendimento': 'Rua das Margaridas, 123 - Boa Vista, Recife - PE, 50090-000',
            'estado': 'PE',
            'lat': '-34.911111',
            'long': '-8.048765',
            'pessoas': 'Luana Santos',
            'profissao': 'Psiquiatra',
            'regiao': 'Nordeste',
        },
        {
            'bairro': 'Parnamirim',
            'cep': '52080-000',
            'cidade': 'Recife',
            'clinica': 'Clínica Saúde Ativa',
            'contato': '81987776655',
            'email': 'joaosaudeativa@email.com',
            'endereco_atendimento': 'Av. dos Lírios, 321 - Parnamirim, Recife - PE, 52080-000',
            'estado': 'PE',
            'lat': '-34.910987',
            'long': '-8.046789',
            'pessoas': 'João Oliveira',
            'profissao': 'Ortopedista',
            'regiao': 'Nordeste',
        },
    ]

    for item in data:
        new_item = {
            'id': str(uuid4()),
            'name': item['clinica'],
            'phone': item['contato'],
            'email': item['email'],
            'addres': {
                'region': item['regiao'],
                'state': item['estado'],
                'city': item['cidade'],
                'neighbourhood': item['bairro'],
                'zip_code': item['cep'],
                'lat': item['lat'],
                'long': item['long'],
                'addres': item['endereco_atendimento'],
            },
            'responsible_person': {
                'name': item['pessoas'],
                'profession': item['profissao'],
            },
            'createdAt': datetime.now(),
        }

        new_data.append(new_item)

    for clinic in new_data:
        collection.document(clinic['id']).set(clinic)


if __name__ == '__main__':
    criar_todas_as_clinicas_no_firestore()
